server:
  port: 8010
  host: localhost

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: service-core
  datasource:
    url: jdbc:mysql://localhost:3306/srb?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 159919
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #------------------redis缓存配置------------
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    #    password: 159919
    # 连接超时时间（毫秒）
    timeout: 5000
    # redis连接池
    jedis:
      pool:
        # 连接池中的最小空闲连接数
        min-idle: 10
        # 连接池中的最大空闲连接数
        max-idle: 500
        # 连接池中的最大连接数
        max-active: 2000
        # 连接池中的最大等待时间（毫秒）连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.245.111:8848
        username: nacos
        password: nanos
        namespace: public

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        writeTimeout: 10000
        # 是否开启调试模式
        debug: true
  sentinel:
    enabled: true
logging:
  level:
    com.titxu.core.client.SmsClient: DEBUG
# mybatis plus配置
mybatis-plus:
  # classpath* 为了解决多模块的情况下，mybatis-plus的配置文件路径问题
  # 如果配置为 classpath，默认会查找当前项目下的mapper.xml文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)



## swagger配置
#swagger:
#  # 是否开启swagger
#  enabled: true
#  # 标题
#  title: '接口文档'
#  # 描述
#  description: '描述：微服务核心管理系统'
#  # 版本
#  version: '1.0.0'
#  # 作者信息
#  contact:
#    name: Lion Li
#    email: crazylionli@163.com
#    url: https://gitee.com/JavaLionLi/RuoYi-Cloud-Plus