server:
  port: 9091
  host: localhost

spring:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: service-sms
  #------------------redis缓存配置------------
  redis:
    # Redis数据库索引（默认为 0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    #    password: 159919
    # 连接超时时间（毫秒）
    timeout: 5000
    # redis连接池
    jedis:
      pool:
        # 连接池中的最小空闲连接数
        min-idle: 10
        # 连接池中的最大空闲连接数
        max-idle: 500
        # 连接池中的最大连接数
        max-active: 2000
        # 连接池中的最大等待时间（毫秒）连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000


sms:
  tencent:
    app_id: 1400655082
    secret_id: AKIDDDySfbGela9QQAerqZ2E9nAH8k59xUln # 访问身份验证中用到用户标识
    secret_key: nJZYIkvpSothFVUCdoiLhndCTUEhtnQm # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    template_id: 1355041 # 短信模板id
    sign_name: 我在你身边js公众号
