server:
  port: 8020
  host: localhost

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev
  application:
    name: service-sms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.245.111:8848
        username: nacos
        password: nanos
        namespace: public
logging:
  level:
    com.titxu.sms.client.CoreUserInfoClient: DEBUG
  #------------------redis缓存配置------------
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    #    password: 159919
    # 连接超时时间（毫秒）
    timeout: 5000
    # redis连接池
    jedis:
      pool:
        # 连接池中的最小空闲连接数
        min-idle: 10
        # 连接池中的最大空闲连接数
        max-idle: 500
        # 连接池中的最大连接数
        max-active: 2000
        # 连接池中的最大等待时间（毫秒）连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        writeTimeout: 10000
        # 是否开启调试模式
        debug: true
  sentinel:
    enabled: true

sms:
  tencent:
    app_id: ${APP_ID} #应用ID
    secret_id: ${SECRET_ID} # 访问身份验证中用到用户标识
    secret_key: ${SECRET_KEY} # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    template_id: ${TEMPLATE_ID} # 短信模板id
    sign_name: ${SIGN_NAME}

# swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 标题
  title: '接口文档'
  # 描述
  description: '描述：微服务核心管理系统'
  # 版本
  version: '1.0.0'
  # 作者信息
  contact:
    name: Lion Li
    email: crazylionli@163.com
    url: https://gitee.com/JavaLionLi/RuoYi-Cloud-Plus